api_platform:
    title: Hello API Platform
    version: 1.0.0
    use_symfony_listeners: true   # <-- add this line
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
