# Étape 1 : builder Angular
FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build -- --configuration=production

# Étape 2 : image Nginx
FROM nginx:stable-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=builder /app/dist/front-end/browser /usr/share/nginx/html

# ✅ Copier ton nginx.conf personnalisé
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
